name: 🧪 Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: mysql:8
    #     env:
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 3306:3306
    #     options: >-
    #       --health-cmd="mysqladmin ping --silent"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3
    # services:

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
        - 5432:5432            
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm install

      - name: Install PHP deps
        run: composer install --no-interaction --prefer-dist

      - name: Setup env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Configure DB
        run: |
          php artisan config:clear
          php artisan migrate --force
        # env:
        #   DB_CONNECTION: pgsql
        #   DB_HOST: 127.0.0.1
        #   DB_PORT: 5432
        #   DB_DATABASE: root
        #   DB_USERNAME: root
        #   DB_PASSWORD: 123

        env:
            DB_CONNECTION: pgsql
            DB_HOST: 127.0.0.1
            DB_PORT: 5432
            DB_DATABASE: test_db
            DB_USERNAME: test_user
            DB_PASSWORD: test_pass

      - name: Build Vite
        run: npm run build

      - name: Run Tests
        run: php artisan test